In [4]:
import pandas as pd

# Read the CSV file from root directory
# df = pd.read_csv("../../r_001_3_creative.csv")
df = pd.read_csv("../../data/documents_train_original.csv")
# df = pd.read_csv("../../refinement_results.csv")
df

,Unnamed: 0,resource_id,"user_write_purpose (work, school, personal)",user_profession,title,resource,id,user_write_purpose,user_kyc_profession
0,43917,c8bec9e5-88ee-508c-9e17-19a2b250646b_Light the...,NaN,researcher/academia,Light therapy,Light plays a major role in regulating the pha...,1203895d-2b63-4690-886e-e3ab2a2eb3f0,work,researcher/academia
1,8077,8f80547a-a393-56b0-a194-4d81d46d9b4e_Guiding p...,NaN,researcher/academia,Guiding principles,Gender equity means a fair distribution of ben...,5af0d908-8665-429f-b02c-fe7591920093,work,researcher/academia
2,4295,f8d6f6a2-54cc-53b2-b6b7-5feffd442b5e_The Devel...,NaN,researcher/academia,The Development of Generative AI,This is where we are in the current AI timelin...,90ee438b-7634-42d4-a29b-3118dcb09901,work,researcher/academia
3,21567,77cb6a46-d29b-500d-b423-f87391c87aa3_Healing Tips,NaN,author,Healing Tips,"For optimal results, start making changes in y...",0f42fbac-6f4b-4cd4-90cf-e97d8553b69f,personal,author
4,19902,ubd82owskojrb6gk,NaN,journalist,Movistar Venezuela Expands LTE Network and Pla...,21 Feb 2020\n Movistar Venez...,f33039ce-c093-4e83-a65b-d3a67252cf19,work,journalist
...,...,...,...,...,...,...,...,...,...
2995,11192,c1a3c4d1-fcaa-51bf-9bf2-8d829addb52c_3 Intern...,NaN,researcher/academia,International Labour Organization,"In 1989, the ILO revised its 1957 Convention o...",0b1bb0e0-3aad-495c-a4c0-bb9f6870c7a8,researcher/academia,researcher/academia
2996,9642,ef790c8a-e24c-5089-bfb6-bd00b2cdb682_4. Materi...,NaN,researcher/academia,4. Materials and Methods,A literature review of academic studies publis...,0383d5d7-ecc4-45bf-bbfa-2070079d4e0b,school,researcher/academia
2997,52085,bd2126db-e8d6-53b5-bf5e-2f0a494b1e04_RESEARCH,NaN,researcher/academia,Research,This paper examines the data obtained in an in...,b72865e0-da5a-4234-b978-5162d876a1e9,school,researcher/academia
2998,17167,88528e28-46c4-5e7c-bb96-817990b1802b_Introduction,NaN,product manager,Introduction,Building performance covers a wide variety of ...,b014793f-76b0-4fae-82a9-9096d57bd0ac,work,product manager
2999,63615,c8570f8f-6a6b-5ab0-b749-dae67d653321_Limitations,NaN,researcher/academia,Limitations,These findings should be interpreted in the co...,cee0840a-28df-433a-8005-a04771bbce19,work,researcher/academia

In [14]:
example_005 = df[df['id'] == "51a1f095-cda5-4691-9a41-07da40242b90"]

example_005

,Unnamed: 0,resource_id,"user_write_purpose (work, school, personal)",user_profession,title,resource,id,user_write_purpose,user_kyc_profession
993,29507,tohbelok5ck7bf1u,NaN,it specialist,Turkcell,15 Apr 2020\n Turkish mobile...,51a1f095-cda5-4691-9a41-07da40242b90,work,it specialist

In [15]:
example_005.to_csv("example_005.csv", index=False)